class: pyobs.modules.MultiModule

shared:
  world:
    class: pyobs.utils.simulation.SimWorld
    time: "2020-10-21 22:00:00"


modules:
  cloudcover:
    class: pyobs_cloudcover.application.Application

    image_sender: "tester"

    model:
      class: pyobs_cloudcover.world_model.SimpleModel
      a0: 4.81426598e-03
      F: 2.00000000e+00
      R: 1.06352627e+03
      c_x: 7.57115607e+02
      c_y: 5.11194838e+02

    server:
      url: "localhost"
      port: 8080

    # This is overridden by the test module
    measurement_log:
      url: ""
      bucket: ""
      org: ""
      token: ""

    pipelines:
      night:
        alt_interval:
          start:
          end: -18

        options:
          preprocessor:
            mask_filepath: ""
            bin_size: 2
            bkg_sigma_clip: 3.0
            bkg_box_size: (5, 5)

          catalog:
            filepath: "data/catalog_v50.csv"
            filter:
              alt: 30.0
              v_mag: 7.0
              distance: 0.0

          reverse_matcher:
            sigma_threshold: 4.0
            window_size: 10.0

          cloud_map:
            radius: 7.0

          coverage_info:
            cloud_threshold: 5.5
            zenith_radius: 20

    comm:
      class: pyobs.comm.local.LocalComm
      name: "cloudcover"

  tester:
    class: pyobs_cloudcover.testing.TestModule
    image_path: "data/test_image.fits"

    comm:
      class: pyobs.comm.local.LocalComm
      name: "tester"

vfs:
  class: pyobs.vfs.VirtualFileSystem
  roots:
    cache:
      class: pyobs.vfs.MemoryFile
      #root: .

comm:
  class: pyobs.comm.local.LocalComm
  name: multi

timezone: Europe/Berlin
location:
    longitude: 9.944333
    latitude: 51.560583
    elevation: 201.0000000008158